modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/devsavage/buckets/issues"
license="MIT"

[[mods]]
    modId="buckets"
    version="${file.jarVersion}"
    updateJSONURL="https://api.savagedev.io/mc-mods/buckets/versions?forge=true"
    displayURL="https://nlcc.savagedev.io/minecraft-mods/buckets/"
    displayName="Buckets"
    logoFile=""
    authors="savagedev"
    description='''
    '''


[[dependencies.buckets]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.buckets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18]"
    ordering="NONE"
    side="BOTH"
[[dependencies.buckets]]
    modId="savagecore"
    mandatory=true
    versionRange="[1.17.1-3.3.0,]"
    ordering="BEFORE"
    side="BOTH"