modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/devsavage/buckets/issues"
license="MIT"

[[mods]]
modId="buckets"
version="${file.jarVersion}"
displayName="Buckets"
logoFile=""
credits="Forge"
authors="savagedev"
description='''
'''


[[dependencies.buckets]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.buckets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17]"
    ordering="NONE"
    side="BOTH"